# Nome do Workflow do GitHub Action
name: Generate Snake Animation

# Define quando a Action deve rodar
on:
  # Roda automaticamente em um cronograma (a cada 12 horas)
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você rode a Action manualmente pela aba "Actions" do GitHub
  workflow_dispatch:

# Define os "jobs" (tarefas) que a Action irá executar
jobs:
  build:
    # O tipo de máquina virtual que o job rodará
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código do seu repositório para a máquina virtual
      - uses: actions/checkout@v3

      # 2. Gera a animação da cobrinha
      - uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}

          # Arquivos de saída que serão gerados
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Envia os arquivos gerados para um branch chamado "output"
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          # Token de acesso necessário para fazer o push para o branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
